import "./globals.css";

import I18nProvider from './I18nProvider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <meta name="application-name" content="Todos os passos contam" />
        <meta name="description" content="Uma plataforma de submissão de kilómetros para a campanha Todos os passos contam da Fundação Galp" />
        <link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png" />
        <link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png" />
      </head>
      <body>
		<I18nProvider>
          <main className="w-full flex items-center justify-center">
            {children}
          </main>
		</I18nProvider>
      </body>
    </html>
  );
}
